title: Soft Skill Series
description: A complete series about enhancing your soft skills for a better personal and professional life
baseurl: ""  # Laat dit leeg als je site geen subdirectory heeft
url: "http://localhost:4000"  # Dit is de lokale URL, wijzig deze voor productie

theme: cvless

# Site settings
taglong: A complete series about enhancing your soft skills for a better personal and professional life
tagshort: Soft Skill Series

# Author settings
author:
  name: Drake W. Fitter
  email: drake.w.fitter@gmail.com
  photo: assets/files/photo.jpg  # Controleer of de foto hier staat

# Social media links
social:
  facebook: Drake W Fitter
  # github: username
  # instagram: username
  # linkedin: username
  # stackoverflow: 0000000/username
  # x: username

# Build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
