# Netlify configuration file

# Build settings (optioneel, afhankelijk van je setup)
<<<<<<< HEAD

[build]
  base = "softskills"     # Submap waar Netlify moet werken
  publish = "softskills/_site"  # Map die Netlify moet publiceren
  command = "jekyll build"      # Build-command om de site te genereren

=======
[build]
  publish = "_site"         # De folder waar je site-bestanden staan na build
  command = "jekyll build"  # Build-command voor Jekyll
  functions = "functions"   # (optioneel) Locatie van serverless functions
>>>>>>> eacf6f75f99d0ae6b617c143df15baaf986672d6

# Redirects voor Netlify Identity
[[redirects]]
  from = "/admin/#/invite"
  to = "/admin/"
  status = 200

[[redirects]]
  from = "/admin/#/reset"
  to = "/admin/"
  status = 200

<<<<<<< HEAD
[[redirects]]
  from = "/.netlify/identity/*"
  to = "/admin/"
  status = 200
  force = true
=======
#[[redirects]]
#  from = "/.netlify/identity/*"
#  to = "/admin/"
# status = 200
# force = true
>>>>>>> eacf6f75f99d0ae6b617c143df15baaf986672d6

# (Optioneel) Overige redirects, bijvoorbeeld voor legacy-URL's
[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301
